### PR TITLE
Make it working with latest SynapsePM plugin.

### PR DESCRIPTION
**Pull request by wolfg1969**

### CODE REVIEW

**Comment by JackboyPlay** [comment]
I dont uderstand the usage of this update!
SynapsePM is a Java plugin and this plugin in php right?

**Comment by Aericio** [comment]
SynapsePM is a PHP plugin... Nemisys is Java.

**Comment by wolfg1969** [comment]
@Aericio right. 
BTW, is this project abandoned?

**Comment by Aericio** [comment]
Yeah, it is. The people who made this (i think) don't have time to update the plugin. dktapps and other people don't really understand how the plugin works so they don't update it ¯\_(ツ)_/¯

**Comment by wolfg1969** [comment]
@Aericio OK. Just put the changes here if someone needs it.  :-)

**Comment by PeratX** [comment]
This should be accepted.

**Comment by remotevase** [comment]
It really should... @PeratX cant you accept it? U are a member...

**Review by FunnyBuddys — APPROVED** [review]

**Comment by Aericio** [comment]
I don't think this is needed now... cuz of transfer packet

**Comment by PeratX** [comment]
DEPRECATED. PocketMine standard is mess.

**Pull request closed without merging**
